package com.passbolt.mobile.android.core.policies.usecase

class PasswordPoliciesFileName(
    userId: String,
) {
    val name = PASSWORD_POLICIES_FILE_NAME_FORMAT.format(userId)

    companion object {
        private const val PASSWORD_POLICIES_FILE_NAME = "password_policies_settings"
        private const val PASSWORD_POLICIES_FILE_NAME_FORMAT = "${PASSWORD_POLICIES_FILE_NAME}_%s"

        const val KEY_DEFAULT_GENERATOR = "DEFAULT_GENERATOR"
        const val KEY_PASSWORD_GENERATOR_LENGTH = "PASSWORD_GENERATOR_LENGTH"
        const val KEY_PASSWORD_GENERATOR_MASK_UPPER_ENABLED = "PASSWORD_GENERATOR_MASK_UPPER_ENABLED"
        const val KEY_PASSWORD_GENERATOR_MASK_LOWER_ENABLED = "PASSWORD_GENERATOR_MASK_LOWER_ENABLED"
        const val KEY_PASSWORD_GENERATOR_MASK_DIGIT_ENABLED = "PASSWORD_GENERATOR_MASK_DIGIT_ENABLED"
        const val KEY_PASSWORD_GENERATOR_MASK_PARENTHESIS_ENABLED =
            "PASSWORD_GENERATOR_MASK_PARENTHESIS_ENABLED"
        const val KEY_PASSWORD_GENERATOR_MASK_EMOJI_ENABLED = "PASSWORD_GENERATOR_MASK_EMOJI_ENABLED"
        const val KEY_PASSWORD_GENERATOR_MASK_CHAR1_ENABLED = "PASSWORD_GENERATOR_MASK_CHAR1_ENABLED"
        const val KEY_PASSWORD_GENERATOR_MASK_CHAR2_ENABLED = "PASSWORD_GENERATOR_MASK_CHAR2_ENABLED"
        const val KEY_PASSWORD_GENERATOR_MASK_CHAR3_ENABLED = "PASSWORD_GENERATOR_MASK_CHAR3_ENABLED"
        const val KEY_PASSWORD_GENERATOR_MASK_CHAR4_ENABLED = "PASSWORD_GENERATOR_MASK_CHAR4_ENABLED"
        const val KEY_PASSWORD_GENERATOR_MASK_CHAR5_ENABLED = "PASSWORD_GENERATOR_MASK_CHAR5_ENABLED"
        const val KEY_PASSWORD_GENERATOR_EXCLUDE_LOOK_ALIKE_ENABLED =
            "PASSWORD_GENERATOR_EXCLUDE_LOOK_ALIKE_ENABLED"

        const val KEY_PASSPHRASE_GENERATOR_WORDS_COUNT = "PASSPHRASE_GENERATOR_WORDS_COUNT"
        const val KEY_PASSPHRASE_GENERATOR_SEPARATOR = "PASSPHRASE_GENERATOR_SEPARATOR"
        const val KEY_PASSPHRASE_GENERATOR_CASE = "PASSPHRASE_GENERATOR_CASE"

        const val KEY_EXTERNAL_DICTIONARY_CHECK_ENABLED = "EXTERNAL_DICTIONARY_CHECK_ENABLED"
    }
}
